### ISSUE TITLE
Basic help patches

### ISSUE THREAD

**Issue by simonemarin** [zekeadam/VL.Mapper#2]
Hallo this is a feature request for the module: it would really help to have help patches for some basic functions, without the GUI and application states. For example:

- grid editor 2d/3d
- bezier curve editor 2d/3d

I tired to get there by myself but the actual implementation is too bound to local classes and records.

**Comment by zekeadam** [comment]
Hello. I'm not sure what you want. The grideditor is designed to be an internal part of the mapper and not meant to be used in itself and there is no 3d version of it. If you want to make a custom editor for yourself its based on [VL.EditingFramework](https://www.nuget.org/packages/VL.EditingFramework) and [VL.EditingFramework.Skia](https://www.nuget.org/packages/VL.EditingFramework.Skia).

**Comment by zekeadam** [comment]
No response, closing
